Changes for PowerAPI monitoring

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,154 +1,158 @@
-on:
-  push:
-    branches: [ master ]
-    
 env:
-  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-  MAVEN_NASHORN: ""
   DOCKER_RESOURCES: ./model/src/test/resources/docker
-
+  MAVEN_NASHORN: ''
+  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 jobs:
-
-  build-jdk11:
-    name: Test view on Docker (jdk-11)
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-    env:
-      JSQL_DOCKERFILE: 3.8.1-jdk-11-slim
-      MAVEN_NASHORN: -Dnashorn.args=--no-deprecation-warning
-    steps:
-
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          # Disable shallow clone to prevent Sonar warning
-          fetch-depth: 0
-
-      - name: Set up JDK
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: 18
-
-      - name: Set Maven dependencies cache
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-maven-
-
-      - name: Install Maven dependencies
-        run: mvn clean install -DskipTests dependency:tree
-
-      - name: Build project container
-        run: docker build -t jsql:latest --build-arg JSQL_DOCKERFILE -f $DOCKER_RESOURCES/Dockerfile.jsql .
-
-      - name: Unit tests
-        run: $DOCKER_RESOURCES/scripts/run-on-docker-no-network.sh 'cd view/ && mvn clean install -P tests'
-
   build:
+    env:
+      JSQL_DOCKERFILE: ${{ matrix.jdk }}
+      MAVEN_NASHORN: ${{ matrix.nashorn }}
     name: Tests on Docker
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+    - continue-on-error: true
+      name: Set up JDK
+      uses: actions/setup-java@v3
+      with:
+        distribution: temurin
+        java-version: 18
+    - continue-on-error: true
+      name: Set Maven dependencies cache
+      uses: actions/cache@v3
+      with:
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        path: ~/.m2/repository
+        restore-keys: ${{ runner.os }}-maven-
+    - continue-on-error: true
+      name: Install Maven dependencies
+      run: mvn clean install -DskipTests dependency:tree
+    - continue-on-error: true
+      name: Run databases and LAMP
+      run: 'docker-compose -f $DOCKER_RESOURCES/docker-compose.yml build --parallel
+
+        docker-compose -f $DOCKER_RESOURCES/docker-compose.yml up -d
+
+        '
+    - continue-on-error: true
+      name: List images and containers
+      run: docker images && docker container ls
+    - continue-on-error: true
+      name: Database health checks and configuration
+      run: '$DOCKER_RESOURCES/scripts/healthcheck/healthcheck.sh
+
+        $DOCKER_RESOURCES/scripts/buff.sh
+
+        $DOCKER_RESOURCES/scripts/verify.sh
+
+        '
+    - continue-on-error: true
+      name: Build project container
+      run: docker build -t jsql:latest --build-arg JSQL_DOCKERFILE -f $DOCKER_RESOURCES/Dockerfile.jsql
+        .
+    - continue-on-error: true
+      name: Unit and integration tests with Sonar scan
+      run: $DOCKER_RESOURCES/scripts/run-on-docker.sh 'mvn clean install sonar:sonar
+        -P tests org.pitest:pitest-maven:mutationCoverage'
+    - continue-on-error: true
+      name: Databases statistics
+      run: $DOCKER_RESOURCES/scripts/verify.sh
+    - continue-on-error: true
+      name: Copy files and coverage reports from container
+      run: 'mkdir -p shared-resources/model shared-resources/view
+
+        docker cp docker_jsql-container:view/. shared-resources/view
+
+        docker cp docker_jsql-container:model/. shared-resources/model
+
+        docker cp docker_jsql-container:pom.xml shared-resources
+
+        '
+    - continue-on-error: true
+      name: Codecov scan
+      run: cd shared-resources && bash <(curl -s https://codecov.io/bash) || true
+    - continue-on-error: true
+      name: Codacy scan
+      run: cd shared-resources && bash <(curl -Ls https://coverage.codacy.com/get.sh)
+        || true
+    - continue-on-error: true
+      name: Publish coverage
+      run: "git checkout docs\nrm -r view/target/site/ view/target/pit-reports/ model/target/site/\
+        \ model/target/pit-reports/ || echo 'Folder(s) not found'\nFOLDER=view/target/site/jacoco\
+        \ bash -c 'mkdir -p $FOLDER/ && cp -r shared-resources/$FOLDER/. $FOLDER/'\n\
+        FOLDER=model/target/site/jacoco bash -c 'mkdir -p $FOLDER/ && cp -r shared-resources/$FOLDER/.\
+        \ $FOLDER/'\nFOLDER=view/target/pit-reports bash -c 'mkdir -p $FOLDER/ &&\
+        \ cp -r shared-resources/$FOLDER/. $FOLDER/'\nFOLDER=model/target/pit-reports\
+        \ bash -c 'mkdir -p $FOLDER/ && cp -r shared-resources/$FOLDER/. $FOLDER/'\n\
+        git config user.name \"Github Actions\"\ngit config user.email no-response@github.com\
+        \    \ngit pull -s ours  # ignore remote changes when updated by parallel\
+        \ jobs\n# folders view/target model/target contain other build files from\
+        \ 'Install Maven dependencies'\ngit add -f view/target/site/jacoco model/target/site/jacoco\
+        \ view/target/pit-reports model/target/pit-reports\ngit commit -m \"Publish\
+        \ jacoco and pitest reports\"\ngit push\n"
     strategy:
       fail-fast: false
       matrix:
         include:
         - jdk: 3.8.6-eclipse-temurin-18
-          nashorn: ""
+          nashorn: ''
         - jdk: 3.9.3-eclipse-temurin-20
-          nashorn: ""
+          nashorn: ''
+  build-jdk11:
     env:
-      JSQL_DOCKERFILE: ${{ matrix.jdk }}
-      MAVEN_NASHORN: ${{ matrix.nashorn }}
+      JSQL_DOCKERFILE: 3.8.1-jdk-11-slim
+      MAVEN_NASHORN: -Dnashorn.args=--no-deprecation-warning
+    name: Test view on Docker (jdk-11)
+    runs-on: self-hosted
     steps:
-    
-    - name: Checkout code
+    - continue-on-error: true
+      name: Checkout code
       uses: actions/checkout@v3
       with:
-        # Disable shallow clone to prevent Sonar warning
         fetch-depth: 0
-    
-    - name: Set up JDK
+    - continue-on-error: true
+      name: Set up JDK
       uses: actions/setup-java@v3
       with:
         distribution: temurin
         java-version: 18
-    
-    - name: Set Maven dependencies cache
+    - continue-on-error: true
+      name: Set Maven dependencies cache
       uses: actions/cache@v3
       with:
-        path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        path: ~/.m2/repository
         restore-keys: ${{ runner.os }}-maven-
-              
-    - name: Install Maven dependencies
+    - continue-on-error: true
+      name: Install Maven dependencies
       run: mvn clean install -DskipTests dependency:tree
-        
-    - name: Run databases and LAMP
-      run: |
-        docker-compose -f $DOCKER_RESOURCES/docker-compose.yml build --parallel
-        docker-compose -f $DOCKER_RESOURCES/docker-compose.yml up -d
-
-    - name: List images and containers
-      run: docker images && docker container ls
-
-    - name: Database health checks and configuration
-      run: |
-        $DOCKER_RESOURCES/scripts/healthcheck/healthcheck.sh
-        $DOCKER_RESOURCES/scripts/buff.sh
-        $DOCKER_RESOURCES/scripts/verify.sh
-
-    - name: Build project container
-      run: docker build -t jsql:latest --build-arg JSQL_DOCKERFILE -f $DOCKER_RESOURCES/Dockerfile.jsql .
-
-    - name: Unit and integration tests with Sonar scan
-      # Profile usage for skipITs/skipTests (env var MAVEN_OPS not working)
-      # Note: 'mvn sonar:sonar' not working, modules reports not found, use 'mvn verify sonar:sonar' for reliability
-      # Note: gh actions sonarsource/sonarqube-scan-action not working properly => analysis not reliable
-      run: $DOCKER_RESOURCES/scripts/run-on-docker.sh 'mvn clean install sonar:sonar -P tests org.pitest:pitest-maven:mutationCoverage'
-
-    - name: Databases statistics
-      run: $DOCKER_RESOURCES/scripts/verify.sh
-
-    - name: Copy files and coverage reports from container
-      # Sonar scans unmerged reports, Codacy/Codecov requires scanning each files (or reports merged)
-      run: |
-        mkdir -p shared-resources/model shared-resources/view
-        docker cp docker_jsql-container:view/. shared-resources/view
-        docker cp docker_jsql-container:model/. shared-resources/model
-        docker cp docker_jsql-container:pom.xml shared-resources
-
-    - name: Codecov scan
-      run: cd shared-resources && bash <(curl -s https://codecov.io/bash) || true
-
-    - name: Codacy scan
-      run: cd shared-resources && bash <(curl -Ls https://coverage.codacy.com/get.sh) || true
-
-    - name: Publish coverage
-      run: |
-        git checkout docs
-        rm -r view/target/site/ view/target/pit-reports/ model/target/site/ model/target/pit-reports/ || echo 'Folder(s) not found'
-        FOLDER=view/target/site/jacoco bash -c 'mkdir -p $FOLDER/ && cp -r shared-resources/$FOLDER/. $FOLDER/'
-        FOLDER=model/target/site/jacoco bash -c 'mkdir -p $FOLDER/ && cp -r shared-resources/$FOLDER/. $FOLDER/'
-        FOLDER=view/target/pit-reports bash -c 'mkdir -p $FOLDER/ && cp -r shared-resources/$FOLDER/. $FOLDER/'
-        FOLDER=model/target/pit-reports bash -c 'mkdir -p $FOLDER/ && cp -r shared-resources/$FOLDER/. $FOLDER/'
-        git config user.name "Github Actions"
-        git config user.email no-response@github.com    
-        git pull -s ours  # ignore remote changes when updated by parallel jobs
-        # folders view/target model/target contain other build files from 'Install Maven dependencies'
-        git add -f view/target/site/jacoco model/target/site/jacoco view/target/pit-reports model/target/pit-reports
-        git commit -m "Publish jacoco and pitest reports"
-        git push
-
+    - continue-on-error: true
+      name: Build project container
+      run: docker build -t jsql:latest --build-arg JSQL_DOCKERFILE -f $DOCKER_RESOURCES/Dockerfile.jsql
+        .
+    - continue-on-error: true
+      name: Unit tests
+      run: $DOCKER_RESOURCES/scripts/run-on-docker-no-network.sh 'cd view/ && mvn
+        clean install -P tests'
+    strategy:
+      fail-fast: false
   codeql:
     name: CodeQL
     uses: ./.github/workflows/run-codeql.yml
-
   release:
-    needs: [build-jdk11, build, codeql]
     name: Publish
-    uses: ./.github/workflows/release.yml
+    needs:
+    - build-jdk11
+    - build
+    - codeql
     secrets: inherit
+    uses: ./.github/workflows/release.yml
+on:
+  repository_dispatch:
+    types: trigger-ga___maven.yml
